### ISSUE TITLE
New inelliJ IDE not compatible with this plugin

### ISSUE THREAD

**Issue by euneuber** [codebrewer/intellij-platform-dilbert-daily-strip-plugin#34] opened 2022-11-10 09:07 UTC
PHPStorm version:
```
PhpStorm 2022.3 Beta
Build #PS-223.7401.19, built on November 4, 2022
Licensed to PhpStorm EAP user: euneuber@gmail.com
Expiration date: December 4, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.14.21-150400.24.28-default
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    ide.tooltip.initialDelay=992

Non-Bundled Plugins:
    Dilbert (1.9.0.168)
    com.intellij.ideolog (203.0.30.0)
    com.dmarcotte.handlebars (223.7401.10)
    ru.adelf.idea.dotenv (2022.3)
    nl.deschepers.laraveltinker (2.4.0)
    de.beyondco.tinkerwell.tinkerwell (2.0)
    com.laravel_idea.plugin (6.0.0.223)

Current Desktop: KDE
```

Error message:
```
java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:409)
	at java.base/java.util.Timer.schedule(Timer.java:205)
	at org.codebrewer.intellijplatform.plugin.dilbert.DilbertDailyStripPluginImpl.fetchDailyStrip(DilbertDailyStripPluginImpl.java:115)
	at org.codebrewer.intellijplatform.plugin.dilbert.DilbertDailyStripPluginImpl.fetchDailyStrip(DilbertDailyStripPluginImpl.java:108)
	at org.codebrewer.intellijplatform.plugin.dilbert.strategy.CurrentDailyStripProvider$RefreshDailyStripAction.fetchDailyStrip(CurrentDailyStripProvider.java:240)
	at org.codebrewer.intellijplatform.plugin.dilbert.strategy.CurrentDailyStripProvider$RefreshDailyStripAction.actionPerformed(CurrentDailyStripProvider.java:208)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:462)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by codebrewer** [comment] 2022-11-10 18:03
Thanks for the report, @euneuber - I'm able to reproduce the problem and will look at fixing it...

**Comment by codebrewer** [comment] 2022-11-18 22:07
@euneuber A new version of the plugin (1.10.0.314) has been uploaded to the JetBrains plugin repo and is currently pending review, which apparently can take up to 2 business days... Hopefully it'll be available for download early next week 🤞

**Comment by codebrewer** [comment] 2022-11-25 19:21
The dilbert.com site was down for several days but seems to be OK again, and I'm able to fetch the strip using the latest version of the plugin with the 2022.3 RC build of IntelliJ IDEA. I'll close this issue now but please raise another if you're still having problems, @euneuber. Thanks again for the report.

**Closed by codebrewer** 2022-11-25 19:21 UTC
